import React, { Component } from 'react'
import '../assets/stylestabla.css'

export default class Simular extends Component {
  render() {
    return (
      <div>
        <h1>Tabla de Simulación</h1>
        <div class= "container">
            <table>
                <thead>
                    <tr>
                    <th colSpan={9} font-size={20} class="titulo">Simulación</th>
                    </tr>
                    <tr>
                        <th>Día</th>
                        <th>N°Autos a rentar</th>
                        <th>Auto</th>
                        <th>Total disponible</th>
                        <th>N°Dias a alquilar</th>
                        <th>Alquiler</th>
                        <th>Costo ocioso</th>
                        <th>Días no disponible</th>
                        <th>Costo no disponible</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>3</td>
                        <td>toyota</td>
                        <td>2</td>
                        <td>5</td>
                        <td>300</td>
                        <td>50</td>
                        <td>5</td>
                        <td>200</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>3</td>
                        <td>toyota</td>
                        <td>2</td>
                        <td>5</td>
                        <td>300</td>
                        <td>50</td>
                        <td>5</td>
                        <td>200</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>3</td>
                        <td>toyota</td>
                        <td>2</td>
                        <td>5</td>
                        <td>300</td>
                        <td>50</td>
                        <td>5</td>
                        <td>200</td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>3</td>
                        <td>toyota</td>
                        <td>2</td>
                        <td>5</td>
                        <td>300</td>
                        <td>50</td>
                        <td>5</td>
                        <td>200</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>3</td>
                        <td>toyota</td>
                        <td>2</td>
                        <td>5</td>
                        <td>300</td>
                        <td>50</td>
                        <td>5</td>
                        <td>200</td>
                    </tr>
                    <tr>
                        <td>6</td>
                        <td>3</td>
                        <td>toyota</td>
                        <td>2</td>
                        <td>5</td>
                        <td>300</td>
                        <td>50</td>
                        <td>5</td>
                        <td>200</td>
                    </tr>
                    <tr>
                        <td>7</td>
                        <td>3</td>
                        <td>toyota</td>
                        <td>2</td>
                        <td>5</td>
                        <td>300</td>
                        <td>50</td>
                        <td>5</td>
                        <td>200</td>
                    </tr>
                    <tr>
                        <td>8</td>
                        <td>3</td>
                        <td>toyota</td>
                        <td>2</td>
                        <td>5</td>
                        <td>300</td>
                        <td>50</td>
                        <td>5</td>
                        <td>200</td>
                    </tr>
                    <tr>
                        <td>9</td>
                        <td>3</td>
                        <td>toyota</td>
                        <td>2</td>
                        <td>5</td>
                        <td>300</td>
                        <td>50</td>
                        <td>5</td>
                        <td>200</td>
                    </tr>
                    <tr>
                        <td>10</td>
                        <td>3</td>
                        <td>toyota</td>
                        <td>2</td>
                        <td>5</td>
                        <td>300</td>
                        <td>50</td>
                        <td>5</td>
                        <td>200</td>
                    </tr>
                    <tr>
                        <td>11</td>
                        <td>3</td>
                        <td>toyota</td>
                        <td>2</td>
                        <td>5</td>
                        <td>300</td>
                        <td>50</td>
                        <td>5</td>
                        <td>200</td>
                    </tr>
                    <tr>
                        <td>12</td>
                        <td>3</td>
                        <td>toyota</td>
                        <td>2</td>
                        <td>5</td>
                        <td>300</td>
                        <td>50</td>
                        <td>5</td>
                        <td>200</td>
                    </tr>
                    <tr>
                        <td>13</td>
                        <td>3</td>
                        <td>toyota</td>
                        <td>2</td>
                        <td>5</td>
                        <td>300</td>
                        <td>50</td>
                        <td>5</td>
                        <td>200</td>
                    </tr>

                </tbody>
            </table>
        </div>
      </div>
    )
  }
}